version: '3.8'

services:
  mysql-luanda:
    image: mysql:8.0
    container_name: no-luanda
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kwanza2024
      MYSQL_DATABASE: mercadokwanza
    ports:
      - '3360:3306'        # ← mudou de 3306 para 3360
    volumes:
      - ./dados:/docker-entrypoint-initdb.d
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-format=ROW
      --character-set-server=utf8mb4

  mysql-benguela:
    image: mysql:8.0
    container_name: no-benguela
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kwanza2024
      MYSQL_DATABASE: mercadokwanza
    ports:
      - '3361:3306'        # ← mudou de 3307 para 3361
    command: >
      --server-id=2
      --character-set-server=utf8mb4

  mysql-huambo:
    image: mysql:8.0
    container_name: no-huambo
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: kwanza2024
      MYSQL_DATABASE: mercadokwanza
    ports:
      - '3362:3306'        # ← mudou de 3308 para 3362
    command: >
      --server-id=3
      --character-set-server=utf8mb4

  mongodb:
    image: mongo:7.0
    container_name: mongo-kwanza
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: mercadokwanza